name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Move Pom.xml to Root
        run: mv .github/workflows/pom.xml ./pom.xml
      - name: Build and analyze
        env:
          GITHUB_TOKEN: >-
            cd884703-719e-483b-8ebe-80b67d86a64d-ab54a634-76fb-4783-bd20-f1fc012275c5
          SONAR_TOKEN: e62c84adbcfda79e46a9c096fbf892c15140994b
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=neojarvis-testing_cd884703-719e-483b-8ebe-80b67d86a64d-ab54a634-76fb-4783-bd20-f1fc012275c5
          -Dsonar.login=e62c84adbcfda79e46a9c096fbf892c15140994b
      - name: Trigger API
        if: always()
        env:
          API_URL: '${{ secrets.API_URL }}'
          API_SECRET: '${{ secrets.API_SECRET }}'
        run: >
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          API_PAYLOAD="{ \"repo_id\": \"$REPO_NAME\", \"branch_name\":
          \"$BRANCH_NAME\", \"api_secret\": \"$API_SECRET\" }"

          curl -X POST -H "Content-Type: application/json" -d "$API_PAYLOAD"
          $API_URL
